version: '3.7'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./src:/var/www/html"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_SSL_PORT}:443
        tty: true
        environment:
            - APP_KEY=${APP_KEY}
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: /bin/sh -c "
            envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf
            && envsubst '$$NGINX_HOST,$$NGINX_HTTP_PORT,$$MYSQL_HOST,$$MYSQL_PORT,$$MYSQL_DATABASE,$$MYSQL_USER,$$MYSQL_PASSWORD,$$APP_KEY,$$REDIS_HOST,$$REDIS_PORT,$$REDIS_PASSWORD' < /var/www/html/.env.docker > /var/www/html/.env
            && nginx -g 'daemon off;'
            "
        restart: unless-stopped
        depends_on:
            - php
            - mysql
        networks:
            - laravel
            - nginx-proxy

    php:
        image: php:${PHP_VERSION}
        container_name: php
        restart: unless-stopped
        tty: true
        volumes:
            - "./src:/var/www/html"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        restart: unless-stopped
        tty: true
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - "./data/mysql:/var/lib/mysql"
            - "./etc/mysql/mysql.conf:/etc/mysql/conf.d/myconf.conf"
        networks:
            - laravel

    redis:
        image: redis
        container_name: redis
        ports:
            - ${REDIS_PORT}:6379
        restart: unless-stopped
        networks:
            - laravel

    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./src:/app"
        command: install
        restart: unless-stopped
        networks:
            - laravel
networks:
    laravel:
    nginx-proxy: